name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # Change this if your deployment branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install Trunk
        run: cargo install trunk --locked

      - name: Build the Project
        run: trunk build --release

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Publish to Cloudflare Pages
        run: wrangler pages deploy dist --project-name=sb-calculators
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
